Check spelling and links

diff --git a/.github/workflows/check_links.yaml b/.github/workflows/check_links.yaml
--- a/.github/workflows/check_links.yaml
+++ b/.github/workflows/check_links.yaml
@@ -1,28 +1,32 @@
-name: Check links
-
 on:
   push:
   pull_request:
   schedule:
-  - cron: "0 0 16 * *"
+  - cron: "0 0 12 * *"
 
+name: check-links
 
 jobs:
-  check_links:
-
+  check-links:
     runs-on: ubuntu-latest
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-
     steps:
       - uses: actions/checkout@v2
 
-      - name: Remove folders that do not care about broken links
+      - name: Remove lines with false positives
         run: |
-          rm -rf DevelopmentDesign
+          sed -i 's/.*check_links.yaml.*//g' README.md
+          sed -i 's/.*check_spelling.yaml.*//g' README.md
+
+      # If there is a valid external link that fails,
+      # add it to mlc_config.json
+      - name: External links must be checked, do not allow '0' in the 'aliveStatusCodes' of mlc_config.json
+        run: if [[ $(grep --regexp "[^0-9]0[^0-9]" mlc_config.json | wc --lines) == "1" ]]; then echo "FOUND"; exit 42; fi
+
+      - name: Internal links must checked, do not allow '400' in the 'aliveStatusCodes' of mlc_config.json
+        run: if [[ $(grep --regexp "[^0-9]400[^0-9]" mlc_config.json | wc --lines) == "1" ]]; then echo "FOUND"; exit 42; fi
 
       - uses: gaurav-nelson/github-action-markdown-link-check@v1
-
-      #- uses: lycheeverse/lychee-action@v1.2.0
-      #  with:
-      #    fail: true
+        with:
+          config-file: 'mlc_config.json'
